### ISSUE TITLE
Tint Stack Doc Component

### ISSUE THREAD

**Issue by jamesmelzer** [JDRF/spirit#13]
### Deliver

* Skin the component to match the visual style of the overall design system

### Process

Build #14

**Comment by jamesmelzer** [comment]
As shown in this article mockup:
![doc article](https://user-images.githubusercontent.com/1207666/42819019-53c05730-89a0-11e8-8506-abdc103aa8e6.png)

**Comment by jamesmelzer** [comment]
## Peer Review

@patrickmckowen 
@kevinmpowell

**Comment by patrickmckowen** [comment]
@jamesmelzer I prefer using the code font family and color palette only within code blocks.  For the tint stack, perhaps we just use Graphik and grey and white e.g. https://gmkr.io/s/5b4e35db2039e221021e769c/0

Agree we need a code specific color pallete though.  Is there a popular Sublime text theme we can borrow from?

**Comment by jamesmelzer** [comment]
I'll check code palettes. Here's the tint stack with only Graphik. Looks great. 

![screen shot 2018-07-17 at 4 19 38 pm](https://user-images.githubusercontent.com/1207666/42844473-07f89a6a-89e1-11e8-9e86-a685787763ef.png)

**Comment by jamesmelzer** [comment]
Code snippets derive from this base stylesheet:
https://github.com/EightShapes/esds-doc/blob/master/components/code_snippet/code_snippet.scss
