### ISSUE TITLE
Homepage (Doc Site)

### ISSUE THREAD

**Issue by jamesmelzer** [JDRF/spirit#136]
Build may need to wait for appropriate components to be ready (e.g. hero and cards). Or consider building temporary components as placeholders. 

Investigate and potentially enhance doc site with responsiveness (hamburger navigation) at the same time. 

Before deployment - HIDE bottom section and have reviewed by design team (see designs - upcoming)

**Comment by joesnellpdx** [comment]
@ismaeltoure7 

Waiting for the approval of the design task:
https://github.com/JDRF/spirit/issues/137

**Comment by ismaeltoure7** [comment]
@joesnellpdx Layouts reviewed during today's crit. I'll update the files as soon as we have a final decision on hero, logo, and interior page options.

https://share.goabstract.com/cfad6d11-2bda-4c5b-b0be-441da27bd25b

**Comment by joesnellpdx** [comment]
This has been approved and merged. Closing.
