### ISSUE TITLE
Brushes - Technical Exploration

### ISSUE THREAD

**Issue by jamesmelzer** [JDRF/spirit#144]
Explore technical options for expressing JDRF's brand identity "brushes". Are they SVG? Can they be animated, and if so how do we accomplish it? Do we need masking objects in addition to the brushes themselves? 

Brush stroke examples: https://d.pr/i/Lggdt2
Brush mockup examples: https://invis.io/PWG4AT48UE2
Priority component wireframes: https://invis.io/PWG4AT48UE2#/282402581_Priority_UI_Components

**Comment by joesnellpdx** [comment]
Note to Joe:
Add alternative element to display animation on 'white' below animated stroke above image.

Current link:
https://codepen.io/joesnellpdx/pen/de089a11344f71f240c5d16c97862029
