### ISSUE TITLE
Button: Follow Up Pass

### ISSUE THREAD

**Issue by jamesmelzer** [JDRF/spirit#161]
Follow up to the first pass at button in #59 

Two tasks:

1. Resolve feedback from https://github.com/JDRF/spirit/pull/152 ( review comments here )
2. Update minimal button based on recent design changes. Note: token values may accomplish some of this. See #160.
3. Add toggle button ( input checkbox / radio ) - see forms in sketch. Addressed in feedback from pull above, but may need to discuss with Kevin. Add to macro and possibly improve macro conditionals.

**Comment by joesnellpdx** [comment]
@kevinmpowell @jamesmelzer 

Per discussion with Kevin today, do we want to remove / alter use of box shadow for border in this ticket? What is technical strategy?

**Comment by joesnellpdx** [comment]
PR again ready for review:
https://github.com/JDRF/spirit/pull/173#pullrequestreview-138656953

- [ ] @patrickmckowen 
- [ ] @jamesmelzer 
- [ ] @kevinmpowell

**Comment by joesnellpdx** [comment]
Added @patrickmckowen and @james for PR:
https://github.com/JDRF/spirit/pull/173#pullrequestreview-139939683
