### ISSUE TITLE
Layout & Grid - Prototype Layouts in Code

### ISSUE THREAD

**Issue by jamesmelzer** [JDRF/spirit#176]
Build the 3-4 templates explored in #175 at prototype quality, with explicit background colors for columns and gutters, so we can see the layout working at various breakpoints. 

Architectural recommendations requested. Is layout part of the grid? Separate? A separate task will build this out formally.

**Comment by joesnellpdx** [comment]
Notes:

See:
https://app.goabstract.com/projects/e8a6a8d0-cf02-11e7-97e7-85865a55282a/branches/master/files/ED21ABF3-D78E-42A7-A214-C7AEC305BB4E/pages/26EB4B31-0B60-4A06-9ECE-831BA85D3CF2

- Full - width and large containers both have the optional top / bottom padding but set left right padding / margin max width. 
- They also have options for background.
- They also can ( likely will ) contain the grid
- Grid gutter sizing has to be updated per this task ( see link above )

**Comment by kdo** [comment]
Hopefully I'm following the right process, I've opened PR #203 for this ticket.
Thanks!
