### ISSUE TITLE
Reduce Icon Set

### ISSUE THREAD

**Issue by kevinmpowell** [JDRF/spirit#200]
As discussed in the 8/3 Critique, reduce the large icon set down to just the icons that Spirit and the other JDRF products will need to use.

**Comment by ismaeltoure7** [comment]
alert-circle
calendar
check
check-circle
chevron-down
chevron-left
chevron-right
chevron-up
external-link
facebook
help-circle
info
instagram
linkedin
mail
map-pin
phone
play-circle
printer
twitter
user
x
youtube
