### ISSUE TITLE
CDN Release - fonts, CSS, etc. [Doc]

### ISSUE THREAD

**Issue by kevinmpowell** [JDRF/spirit#223]
* [x] @jamesmelzer 
* [x] @patrickmckowen 

Doc is ready for review:
https://docs.google.com/document/d/1f76_iPS3gfiHiKIU93XVHPOjHZwSmu5EhhsluXXPI3Y/edit#

I imagine this doc will be incorporated as a sub section into the larger Getting Started for Developers guide.

**Comment by jamesmelzer** [comment]
Added a couple comments about including the version number consistently in your example URLs. If not relevant (like, with font files?) then please ignore.
