### ISSUE TITLE
Icon Swatch Doc Component

### ISSUE THREAD

**Issue by jamesmelzer** [JDRF/spirit#26]
### Deliver

* Skin the component to match the visual style of the overall design system

### Process

Build #27

**Comment by jamesmelzer** [comment]
This is the strong hover state I mentioned, which gives an on-dark preview. 

Questions

- [ ] Should the on-dark reverse be JDRF blue instead of black?
- [ ] Is showing the in-sprite icon name useful? 
- [ ] If we support click-to-copy, what should it copy? "icon-name" or "icons/spirit.svg#icon-name"

![screen shot 2018-07-27 at 1 40 52 pm](https://user-images.githubusercontent.com/1207666/43337795-c10f1af6-91a2-11e8-89b5-996648243716.png)

**Comment by patrickmckowen** [comment]
@jamesmelzer yes to the first two.  I defer to FEE on what is copied.

**Comment by jamesmelzer** [comment]
### Revised

no sprite name (but call it out clearly in the guidelines)
switched to JDRF blue on hover
click copies the icon name (for code)

![screen shot 2018-07-27 at 3 15 28 pm](https://user-images.githubusercontent.com/1207666/43342291-35c1f82a-91b0-11e8-9ee3-88fe24f69d54.png)

**Comment by jamesmelzer** [comment]
![screen shot 2018-07-27 at 3 33 04 pm](https://user-images.githubusercontent.com/1207666/43342919-5f2b540c-91b2-11e8-88fc-5c2be56e691f.png)
