### ISSUE TITLE
Phone Input Mask

### ISSUE THREAD

**Issue by kevinmpowell** [JDRF/spirit#267]
![screen shot 2018-09-17 at 2 14 15 pm](https://user-images.githubusercontent.com/979463/45644714-fba24d00-ba83-11e8-9e0c-90e23e9eebd5.png)

**Comment by joesnellpdx** [comment]
@patrickmckowen @ismaeltoure7

Issue 185 (closed) initially handled this, but was not completed. There is an existing branch that I have extended that should resolve this issue here:
#279

Closed issue:
#185

**Comment by joesnellpdx** [comment]
This has been reviewed and merged:
https://github.com/JDRF/spirit/pull/279#event-2107163769
