### ISSUE TITLE
Date Input Mask

### ISSUE THREAD

**Issue by kevinmpowell** [JDRF/spirit#268]
![screen shot 2018-09-17 at 2 14 40 pm](https://user-images.githubusercontent.com/979463/45644735-08bf3c00-ba84-11e8-9a5e-9e194fd5426c.png)

*Acceptance Criteria*
* As a user I want to see `MM/DD/YYYY` persisted as I type

**Comment by joesnellpdx** [comment]
@patrickmckowen @ismaeltoure7 

Issue 185 (closed) initially handled this, but was not completed. There is an existing branch that I have extended that should resolve this issue here:
https://github.com/JDRF/spirit/pull/279

Closed issue:
https://github.com/JDRF/spirit/issues/185

**Comment by joesnellpdx** [comment]
This has been reviewed and merged:
https://github.com/JDRF/spirit/pull/279#event-2107163769
