### ISSUE TITLE
Add Missing Icons

### ISSUE THREAD

**Issue by joesnellpdx** [JDRF/spirit#277]
Add missing icons back to sprite / svg output.

Found in page templates using to build.

- Twitter, chevron left & right, youtube, play-circle.
- Check to see what else may be missing

**Comment by joesnellpdx** [comment]
@patrickmckowen 

I need you to check the icons in the library and see what else we may be missing - OR give me the final list you have so I can cross check. 

I will definitely be adding those in the description.

**Comment by patrickmckowen** [comment]
@joesnellpdx see list and related task here: https://github.com/JDRF/spirit/pull/236#pullrequestreview-150301411

**Comment by joesnellpdx** [comment]
This has been approved and merged.
