### ISSUE TITLE
Spirit Button Icon - incorrect size and size modifiers not working

### ISSUE THREAD

**Issue by joesnellpdx** [JDRF/spirit#280]
- Make sure the spirit button icon matches Abstract / Sketch (both the icon and the button size): https://share.goabstract.com/d4d9f3e8-1ef0-4571-8c8d-e94e64858f2c
- Test sizing modifiers - make sure match sketch / abstract
- Test context ( background colors )

**Comment by joesnellpdx** [comment]
In Peer review:
https://github.com/JDRF/spirit/pull/300

**Comment by ismaeltoure7** [comment]
@joesnellpdx I've reviewed this but I am not listed as approver on the merge request.

**Comment by joesnellpdx** [comment]
This has been merged into develop.

Will also need to verify doc site is updated correctly after this is merged (new github ticket)

NOTE:
for all of these updates - will need method to test / remove 'fixes' on .org when next release is pushed.

In this instance:
Need to review cases of .spirit-button--icon-only in css and in codebase output for updates / alterations on .org. In particular - in .social-nav
