### ISSUE TITLE
Long form text - Mobile spacing

### ISSUE THREAD

**Issue by kdo** [JDRF/spirit#281]
Noticed long form text elements spacing on smaller screen doesn't match mocks here:
https://share.goabstract.com/9bb68fec-5705-4672-bd6e-08ef9b93ddee

**Comment by joesnellpdx** [comment]
In peer review:
https://github.com/JDRF/spirit/pull/301

**Comment by ismaeltoure7** [comment]
@joesnellpdx It looks great! Here are a few things I found:
- H3s are missing top padding
- "Lead Headings" section starts with regular headings (duplicates of previous section?)
- Spirit-lead-heading class is applied to H4s, but the description only mentions it being applicable to H1s, H2s and H3s (should it be applied to all headers?)
- Blockquote is missing the 16px left and right padding

**Comment by joesnellpdx** [comment]
This has been approved and merged.
