### ISSUE TITLE
Page Frame Doc Component

### ISSUE THREAD

**Issue by jamesmelzer** [JDRF/spirit#29]
### Deliver

* Skin the component to match the visual style of the overall design system

### Process

Build #28

**Comment by jamesmelzer** [comment]
![page shell - large](https://user-images.githubusercontent.com/1207666/43422623-50dc2ab2-9418-11e8-826f-565e9a0e5939.png)

![page shell - 1256px](https://user-images.githubusercontent.com/1207666/43422626-53a824bc-9418-11e8-849e-494bc6773057.png)

![page shell - under 1256px 1072 shown](https://user-images.githubusercontent.com/1207666/43422629-55b7fd18-9418-11e8-932b-86e317a3307f.png)

**Comment by jamesmelzer** [comment]
Looking for peer review from:

- [ ] @patrickmckowen 
- [ ] @kevinmpowell

**Comment by patrickmckowen** [comment]
@jamesmelzer I've found that 700px is the recommended max-width for containers with long form text.  Perhaps the Code + Example Pairs could extend out beyond the text area e.g. https://invis.io/5EN93MYAUT7#/294908300_Content-Article_-_Blog

**Comment by kevinmpowell** [comment]
@jamesmelzer I really like "no overall max width" but I am concerned about the lack of content to fill the center section and the gulf of whitespace that will exist between content and navigation. This creates a disconnect between the content and navigation which is not as big a deal for the site-level nav, but definitely for the page-level (Table of Contents) nav. I think an overall max width might make sense, or at least keeping the TOC nav anchored to the right side of the content.

>  I've found that 700px is the recommended max-width for containers with long form text. Perhaps the Code + Example Pairs could extend out beyond the text area e.g.
To @patrickmckowen's point, I agree, and typically implement a max width that only applies to text while examples, images, do/don'ts, reference tables, etc. typically stretch to fill the available space.

**Comment by jamesmelzer** [comment]
@kevinmpowell I played with it in HTML and looked at a few examples and I agree. 

Revised:
![page shell - large](https://user-images.githubusercontent.com/1207666/43542104-239cac92-959a-11e8-9e74-677536f4460f.png)

I'll show it in critique, time permitting.

**Comment by patrickmckowen** [comment]
@jamesmelzer I agree with adding a max-width to the main content and keeping the content and page-level nav grouped together with a 32px fixed gutter.  Looks great!
