### ISSUE TITLE
Checkbox issue on iOS

### ISSUE THREAD

**Issue by patrickmckowen** [JDRF/spirit#299]
From Jamie Arkin at Blue State Digital:

As you can see in the [attached] video, when you click the checkbox it doesn’t check. It seems like it goes into a focus state of some sort. You are required to click twice in order for the checkbox to work, then it seems to work perfectly fine.

[spirit-checkbox-error.mov.zip](https://github.com/JDRF/spirit/files/2724843/spirit-checkbox-error.mov.zip)

Jamie suggests this fix:

```
var dragging = false;
$('body').on('touchmove', function() {
	dragging = true;
});

$('body').on('touchstart', function() {
	dragging = false;
});

$('body').on('click, touchend', 'label', function(e) {
	e.preventDefault();
	if (dragging) return;

	var input = $(e.currentTarget).find('input');

	if (input.is(':checked')) {
		input.prop('checked', false);
		return;
	};
	input.prop('checked', true);
});
```

**Comment by joesnellpdx** [comment]
@patrickmckowen @lauralvictor 

PR here:
https://github.com/JDRF/spirit/pull/303

**Comment by joesnellpdx** [comment]
This has been approved and merged
