### ISSUE TITLE
Release Details Doc Component

### ISSUE THREAD

**Issue by jamesmelzer** [JDRF/spirit#30]
### Deliver

* Skin the component to match the visual style of the overall design system

### Process

Build #31

**Comment by jamesmelzer** [comment]
Release History page design:
https://share.goabstract.com/febdc8b2-d44d-4078-bd43-97fba40c389c

Plus draft content for the next couple releases:
https://docs.google.com/document/d/1k_dkP0kfhNpg-r5rUnxuYEfG2fEErLePwyLi3isVz5s/edit#
(Key assumption: we're going to fast-forward nearly everything into the next release, which could be the first "feature" release. The alternative is I do some digging and back-date components appropriately. Value seems low. )

Feedback sought from 
- [ ] @patrickmckowen 
- [ ] @kevinmpowell

**Comment by jamesmelzer** [comment]
PREVIEW 
![doc site - release history](https://user-images.githubusercontent.com/1207666/44423487-3764f800-a554-11e8-9948-3fdc7137a0e4.png)

**Comment by kevinmpowell** [comment]
## Feedback
Don't back-date. Release 1.0.0 can start the official history.

I like the layout. 

I don't think the release page is the place to educate on Semver basics. I'd use that space to describe the sort of details one can expect to see on this page.

"We'll document changes to components, visual style, tokens, etc." - something along those lines.

**Comment by patrickmckowen** [comment]
As I understand it, viewing past versions of the docs is helpful for viewing old versions after a major release with breaking changes.  I wonder if we only include the View Docs link for past major releases?

**Comment by jamesmelzer** [comment]
@patrickmckowen That's an interesting approach. 

Extending that logic... major releases contain breaking changes. There's nothing blocking products from upgrading to the latest minor release (except ongoing integration effort, potentially), so there's little value in maintaining documentation to previous minor releases. 

This approach would certainly minimize the number of versions to store, link to, and support. 

The flip side is, Spirit may not have a major release for years. You might increment up to 1.45.0 before you needing to roll over to 2.0.0. The value of having the archive of v1.0.0 is low in this scenario, since your product adoptions might come at 1.1, 1.4, 1.8, and 1.27 (for example). 

For the product that adopts at 1.8, they might be keen to see 1.8 documentation archived, but don't care about 1.0.0. 

My recommendation is to continue archiving at minor releases, so products can self-select what's relevant for them.
