### ISSUE TITLE
Remove Tile component from system

### ISSUE THREAD

**Issue by patrickmckowen** [JDRF/spirit#304]
After piloting Spirit with the JDRF.org redesign, we've determined there isn't the demand for this component to justify including it in the system.

- remove tile from project
- preserve necessary styles to re-purpose on .org (or elsewhere) as needed
- once removed from system - update all issues pertaining to tile found in project

**Comment by joesnellpdx** [comment]
PR found here: https://github.com/JDRF/spirit/pull/305

**Comment by joesnellpdx** [comment]
This has been reviewed and merged.
