### ISSUE TITLE
List Component Refinements

### ISSUE THREAD

**Issue by ismaeltoure7** [JDRF/spirit#306]
Our review of the redesigned JDRF.org helped us identify a few improvements to increase the legibility of our List components. The following spec sheets details the updates for desktop and mobile, which include font weight, line height, margin, divider adjustments, along with the addition of a user avatar option.

Desktop: https://share.goabstract.com/e27e2e39-dc2e-4dfb-aa43-5583ee6ffc8f

Mobile: https://share.goabstract.com/5669400f-8408-4788-ad3d-65abdbf5871a

**Comment by joesnellpdx** [comment]
This has been merged / approved.

https://github.com/JDRF/spirit/pull/329
