### ISSUE TITLE
Card Component Refinements

### ISSUE THREAD

**Issue by ismaeltoure7** [JDRF/spirit#307]
A/B tests conducted since the JDRF.org redesign showed a significantly reduced bounce rate when we added elevation to Card components on our T1D Resources landing page. This update, along with text size and spacing adjustments can be found on the following spec sheets.

Desktop: https://share.goabstract.com/bc46eaa8-5e95-4b47-a4b7-6bf2a8aa5192

Mobile: https://share.goabstract.com/e6328374-7be3-42ab-b0f9-ace74a6482e9

**Comment by joesnellpdx** [comment]
@ismaeltoure7 
@lauralvictor 

This is ready for Peer Review.
See:
https://github.com/JDRF/spirit/pull/341

**Comment by joesnellpdx** [comment]
This has been approved and merged
