### ISSUE TITLE
Brush

### ISSUE THREAD

**Issue by ismaeltoure7** [JDRF/spirit#309]
Guidelines doc
Example/code pairs
Do/Don't examples, if needed
Style reference table
Macro reference

https://drive.google.com/open?id=1mpMKfHCembgI3kWslWtiJP2cD2mqB5lK1teuDOeP2Wc

**Comment by joesnellpdx** [comment]
@ismaeltoure7 
Made comments and some updates in doc. Assigning back to you.

**Comment by jamesmelzer** [comment]
Cut into 1.0 and "2.0?) versions, so we can remove all the out-of-scope items. 

Pass any edits back to @ismaeltoure7 .

**Comment by jamesmelzer** [comment]
@ismaeltoure7 I make a backup copy of the full Brush doc, and cut out all the sections that aren't in 1.0. I think the resulting doc is short by still useful. 

- [ ] Review this doc
- [ ] Assign the pub task when you approve

Original for review: https://docs.google.com/document/d/1mpMKfHCembgI3kWslWtiJP2cD2mqB5lK1teuDOeP2Wc/edit#

Archive of Brush 2.0 content:
https://docs.google.com/document/d/1_bS5eLNpOFiEU1L8gIEOS4yESFAPSOhsd3Da3TF1nv8/edit

**Comment by ismaeltoure7** [comment]
@jamesmelzer All good! I added a suggestion to remove the first image, as it won't be achievable in v1.

**Comment by jamesmelzer** [comment]
Accepted your change. Closing this issue and publishing.
