### ISSUE TITLE
Normalize - why used in .org and should Spirit reset be updated

### ISSUE THREAD

**Issue by joesnellpdx** [JDRF/spirit#312]
Normalize is used in JDRF.org. Why? 

- investigate if there are resets that needed to be added to Spirit
- add resets to Spirit
- test resets across library

**Comment by joesnellpdx** [comment]
.org styles affected by normalize:

* body {margin: 0 } - no body reset on Spirit - need this in .org
* no margin reset in `spirit-typography-reset` mixin - therefore, unless explicit or inside `spirit-long-form-text`(`spirit-h1`) and spirit-display classes (`spirit-display-1`)). See heading here: https://www.jdrf.org/impact/

The reset of the reset items in the customized normalize used in .org are either clearly overridden by spirit classes (i.e. button) or don't exist in spirit (i.e. optgroup).

Normalize could be removed, but it hurt to have the reset in place for items not in Spirit. 

@jamesmelzer 
@kevinmpowell 

1) Should we have a reset for 'body' in Spirit - or should that be up to the consuming property? Shoud that be documented?
2) Should there be a margin reset in spirit-typography-reset?
3) Any issue with using normalize in .org - added in zip below?

[_normalize.scss.zip](https://github.com/JDRF/spirit/files/2858196/_normalize.scss.zip)

**Comment by kevinmpowell** [comment]
> 1. Should we have a reset for 'body' in Spirit - or should that be up to the consuming property? Shoud that be documented?

We typically don't put any sort of global reset into design systems. This allows adopting teams to govern their own reset and avoids competing resets. This could be documented in the getting started guide.

> 2. Should there be a margin or padding reset in spirit-typography-reset?
I wouldn't recommend this. In most cases the margin/padding required for text elements is going to be explicitly set in the component. In the example provided: https://www.jdrf.org/impact/, that `h1` isn't part of a Spirit component, so it wouldn't be affected by `spirit-typography-reset` anyway, unless `spirit-typography-reset` is being applied to the `body` or something, which I wouldn't recommend. The intent for `spirit-typography-reset` is to reset typography values at the component level.

> 3. Any issue with using normalize in .org - added in zip below?
The components should be designed to be robust against any impacts from outside CSS. So no issues expected from that angle.

**Comment by joesnellpdx** [comment]
@jamesmelzer One further action item: should we provide direction for the body / html reset for consuming properties somewhere? Or ... at least mention that is the discretion of the property? Maybe in getting started?

**Comment by ismaeltoure7** [comment]
@joesnellpdx adding @lauralvictor for the BSD h1 issue ticket

**Comment by jamesmelzer** [comment]
I like the idea of mentioning a product's responsibility to provide an overall reset in Getting Started.

**Comment by joesnellpdx** [comment]
@jamesmelzer @ismaeltoure7 Are we good closing this task? I do not see any further action needed.

**Comment by jamesmelzer** [comment]
@ismaeltoure7 I'm fine closing it. I unassigned myself.
I made the follow up ticket already https://github.com/JDRF/spirit/issues/338

**Comment by lauralvictor** [comment]
@joesnellpdx I've asked Jaime at BSD, and she responded “I don’t know why Normalized is used”. I also see that there are no edits to normalize.scss in Beanstalk: https://jdrf.beanstalkapp.com/jdrf-org/history/themes/jdrf-spirit/assets/scss/frontend/10up/base/_normalize.scss

**Comment by lauralvictor** [comment]
@joesnellpdx I've created a task for Jaime at BSD to address this issue on the Impact template styling: https://www.wrike.com/open.htm?id=321027609

**Comment by ismaeltoure7** [comment]
Thanks @lauralvictor !

**Comment by joesnellpdx** [comment]
This has been resolved. No further action needed.
