### ISSUE TITLE
Class Reference Doc Component

### ISSUE THREAD

**Issue by jamesmelzer** [JDRF/spirit#35]
### Deliver

* Skin the component to match the visual style of the overall design system

### Process

Build #34 

![screen shot 2018-07-26 at 1 40 39 pm](https://user-images.githubusercontent.com/1207666/43278660-b77e7226-90d9-11e8-8859-bcd1c6712140.png)

**Comment by jamesmelzer** [comment]
Looking for peer review from:

- [ ] @patrickmckowen 
- [ ] @ismaeltoure7 

Available in Abstract branch `doc site components` or pictured in the ticket above.

**Comment by ismaeltoure7** [comment]
Looks great! And it's very close to our current table styles. The only things I would consider are doubling the space between columns and increasing the the thickness of the header's bottom border to 3 or 4px. @patrickmckowen thoughts?
