### ISSUE TITLE
Getting Started Design Links

### ISSUE THREAD

**Issue by joesnellpdx** [JDRF/spirit#368]
Make sure the getting started design links are accurate.

See the live representation here:
https://jdrf.design/getting-started.html#for-designers

- Spirit UI Sketch Library
- Spirit Marketing UI Kit

**Comment by joesnellpdx** [comment]
@ismaeltoure7 

I noticed these links don't work for me - so added a ticket for you to verify / update if needed.

**Comment by ismaeltoure7** [comment]
@joesnellpdx @patrickmckowen I've updated the "Add Spirit UI Sketch Library" and "Download Spirit Marketing UI Kit" sections to reflect the switch from Sketch Cloud to Abstract. https://docs.google.com/document/d/1zGl8aIkrjJVgAnC2_9vfvPaOrli-XSkDq3WeKmW7HMo/

**Comment by joesnellpdx** [comment]
@ismaeltoure7 I left a couple comments in the doc. Otherwise looks good!

**Comment by ismaeltoure7** [comment]
Thx! @joesnellpdx I've updated based on your feedback. https://docs.google.com/document/d/1zGl8aIkrjJVgAnC2_9vfvPaOrli-XSkDq3WeKmW7HMo/

**Comment by joesnellpdx** [comment]
@ismaeltoure7 Looks great! Approved!

**Comment by ismaeltoure7** [comment]
@joesnellpdx @patrickmckowen I've updated the file per our earlier discussion.

**Comment by joesnellpdx** [comment]
@ismaeltoure7 

- updated links

Is this ready to sign off?

In doc site see `/getting-started.html#for-designers`
