### ISSUE TITLE
Refine Form Grid

### ISSUE THREAD

**Issue by patrickmckowen** [JDRF/spirit#371]
Maintain a 16px gutter for grid elements within a form across all breakpoints. 

Designs call for a reduced grid gutter on forms at breakpoints beyond 1080px to not expand to 32px - as is standard in the Spirit grid, but maintain 16px.

See design update here:
https://app.goabstract.com/projects/e8a6a8d0-cf02-11e7-97e7-85865a55282a/branches/61b5afba-3271-4fe0-bae7-10e9f48f4520/commits/0340a4ef751b06264e151998c16fd94b417869a6/files/8D03A624-1483-4975-B271-BB24C2572BA6/layers/1DF455E0-1FC5-4EB8-9612-1A2915E27A05

Options - need to determine before engineering:
1) Add styles to `.spirit-row` and `[class*='spirit-col-']` when nested within a `<form>` component that maintains 16px gutter
2) Add modifier to `.spirit-row` and `[class*='spirit-col-']` to maintain 16px gutter at all breakpoints that can be used across components with more universal control

We have decided to go with option 1.

**Comment by joesnellpdx** [comment]
@patrickmckowen @ismaeltoure7 I updated the comment and posed the engineering question. 

What are your thoughts?

**Comment by ismaeltoure7** [comment]
@joesnellpdx Since this only impacts forms, option 1 seems to make the most sense.

**Comment by joesnellpdx** [comment]
@ismaeltoure7 @patrickmckowen I will move forward as a child nested style of a `<form>` and update the description of the issue.
