### ISSUE TITLE
Sketch Library + Marketing UI Kit Update

### ISSUE THREAD

**Issue by ismaeltoure7** [JDRF/spirit#378]
Update the Sketch Library and Marketing UI Kit files to reflect the refinements made to the Card component.

Library: https://share.goabstract.com/cad2c9a5-5798-4551-b26d-1c51c47dc14a
Marketing UI Kit: https://share.goabstract.com/d4745d70-8d09-4da9-b768-9aeb1f228cf3

**Comment by joesnellpdx** [comment]
@ismaeltoure7 

1. Should these links be on the master branch?
2. Should these links be focused on the parent item (Library) vs child (Card):
     Library: https://app.goabstract.com/projects/e8a6a8d0-cf02-11e7-97e7-85865a55282a/branches/45f0fbab-c91c-4c8a-b931-9f027c0c21fc/files/4B5B141B-AD52-4BB2-AA44-3DA3263F261E?changed=true
     vs Card: https://app.goabstract.com/projects/e8a6a8d0-cf02-11e7-97e7-85865a55282a/branches/45f0fbab-c91c-4c8a-b931-9f027c0c21fc/files/4B5B141B-AD52-4BB2-AA44-3DA3263F261E/pages/F7DE891E-EC82-4F8F-A9A0-90D1E17249C5?changed=true

**Comment by ismaeltoure7** [comment]
@joesnellpdx 
1. Yes, this branch will be merged into master, once it's approved.
2. Yes, once merged into master, the link will be to the library itself

**Comment by joesnellpdx** [comment]
@ismaeltoure7 
Cool!

I approve, but want to make sure I get the live links for the doc site before we go to 1.0.0.

**Comment by ismaeltoure7** [comment]
A few colors and icons are not appearing in the updated shared library.

**Comment by joesnellpdx** [comment]
@ismaeltoure7 

Holding release until this is updated with direction or that all is working and links are correct in doc site.

**Comment by ismaeltoure7** [comment]
@joesnellpdx Good to go. The files have been updated and sync'ed (same links).
