### ISSUE TITLE
Document Release/Publish Process

### ISSUE THREAD

**Issue by jamesmelzer** [JDRF/spirit#4]
### Deliver

* Basic instructions (Google doc, internal use only)

see Setup #3

**Comment by kevinmpowell** [comment]
Ready for review by:
* [ ] @jamesmelzer 
* [ ] @joesnellpdx 

Doc: https://docs.google.com/document/d/1vdmvckYJFMNfDn6qk7TOdT8v6wtkNOxg5EdSiy2Fc4U/edit#

**Comment by joesnellpdx** [comment]
@kevinmpowell approved. looks great!

**Comment by jamesmelzer** [comment]
I added made a new Release details doc to accompany this process. That way we can get the editorial part of the release out of the way beforehand. 
https://docs.google.com/document/d/1k_dkP0kfhNpg-r5rUnxuYEfG2fEErLePwyLi3isVz5s/edit

Otherwise, looks great.
