### ISSUE TITLE
Getting Started

### ISSUE THREAD

**Issue by jamesmelzer** [JDRF/spirit#6]
### Deliver

* Outline basics startup steps for two "user" audiences

1. Developers looking to integrate the design system into their product
2. Designers looking to use core assets, particularly the sticker sheet

### Process

Pub #7

**Comment by patrickmckowen** [comment]
Looking for PR from:

- [ ] @jamesmelzer 
- [ ] @ismaeltoure7 

https://docs.google.com/document/d/1zGl8aIkrjJVgAnC2_9vfvPaOrli-XSkDq3WeKmW7HMo/edit?usp=sharing

**Comment by jamesmelzer** [comment]
Added some comments suggestions. Scope looks right for designers. 

Big question: should we have a single, long "Getting Started" page with sections for design and develop, or two pages?

**Comment by ismaeltoure7** [comment]
Went through all the steps listed. Looks good!

**Comment by jamesmelzer** [comment]
This one looks done. Want to close it out? We're got #7 in the wings to publish it.
